#! /bin/sh
echo "#version 330 core

uniform vec3      iResolution;           // viewport resolution (in pixels)
uniform float     iGlobalTime;           // shader playback time (in seconds)
uniform vec4      iMouse;                // mouse pixel coords
uniform vec4      iDate;                 // (year, month, day, time in seconds)
uniform float     iSampleRate;           // sound sample rate (i.e., 44100)
uniform sampler2D iChannel0;             // input channel. XX = 2D/Cube
uniform sampler2D iChannel1;             // input channel. XX = 2D/Cube
uniform sampler2D iChannel2;             // input channel. XX = 2D/Cube
uniform sampler2D iChannel3;             // input channel. XX = 2D/Cube
uniform vec3      iChannelResolution[4]; // channel resolution (in pixels)
uniform float     iChannelTime[4];       // channel playback time (in sec)
" > fragment.glsl

if [ "$1" != "" ]
then
	cat "$1" >> fragment.glsl
else
	echo "
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
	discard;
}" >> fragment.glsl
fi

echo "
void main() {
    mainImage(gl_FragColor, gl_FragCoord.xy);
}" >> fragment.glsl

echo running

./RunWebGL $2 $3
